# Generated by Django 5.1.1 on 2024-12-09 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('E_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('e_gen', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pin_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Pid', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('first_name_p', models.CharField(max_length=12)),
                ('last_name_p', models.CharField(max_length=10)),
                ('dob_p', models.DateField(verbose_name='Date of Birth')),
                ('gender_p', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('mob_num_p', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must start with 6, 7, 8, or 9 and be exactly 10 digits long.', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True)),
                ('age_p', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_no', models.AutoField(primary_key=True, serialize=False)),
                ('app_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('R_ID', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('availability', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('E_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hmng.employee')),
                ('department', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('E_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hmng.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('E_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hmng.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('B_ID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmng.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('R_ID', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmng.patient')),
            ],
        ),
    ]
