# Generated by Django 5.1.1 on 2024-12-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender_p',
            field=models.CharField(max_length=1),
        ),
    ]
